### ISSUE TITLE
Display regression on form input on smartphone

### ISSUE THREAD

**Issue by DSMejantel** [sqlpage/SQLPage#652] opened 2024-10-25 20:15 UTC
### Introduction

The two arrows to increase or decrease on the right side of a 'number type' input with step are no more visible on smartphone.

### To Reproduce
This is what I can see on my computer :
![image](https://github.com/user-attachments/assets/9cc3b77f-e409-4a4a-8f92-3f94d061ee93)

```sql
-- SELECT 'product_quantity[]' AS name,
    categorie || ' en pots de '||produits||' (Lot : '||lot||')' AS label,
    coalesce(reste-vendus,reste) ||' en stock. ' || printf("%.2f", prix) || ' € l''unité.' as description,
    'number' AS type,
    1 as step,
    0 as min,
    coalesce(reste-vendus,reste) as max,
    0 as value
FROM produits
```

### Version information

 - OS: Ubuntu
 - Database SQLite
 - SQLPage Version [0.29]:

**Comment by lovasoa** [comment] 2024-10-25 21:39
Hello ! Is this really a regression ? Did the same smartphone browser display arrows on number inputs in a previous version of sqlpage ?

I think it's just that mobile browser tend not to add arrows to number inputs, because they would be too small to touch anyways...

**Comment by lovasoa** [comment] 2024-11-08 12:57
Hi @DSMejantel ! Any news on this ? Were you able to reproduce the different behaviors by running different versions of sqlpage and opening the pages on the same mobile browser ? If so, can you provide a simple .sql file for reproduction, and screenshots of the two behaviors ?

**Comment by lovasoa** [comment] 2024-11-10 19:18
I'm closing this issue, I'll reopen it if we get a reproduction.

**Closed** 2024-11-10 19:18 UTC
Labels: bug
