### ISSUE TITLE
Timeout in requests with sqlpage.fetch()

### ISSUE THREAD

**Issue by srcarvalho12** [sqlpage/SQLPage#696] opened 2024-11-16 19:20 UTC
I'm using the MariaDB database, and fetch requests are not working, even the example:

```sql
set url = 'https://nominatim.openstreetmap.org/search?format=json&q=' || sqlpage.url_encode($user_search)
set api_results = sqlpage.fetch($url);

select 'map' as component;
select $user_search as title,
  CAST($api_results->>0->>'lat' AS FLOAT) as latitude,
  CAST($api_results->>0->>'lon' AS FLOAT) as longitude;
```

I'm always getting timeout, in any request I'm testing, could you help me, pls?!

**Comment by lovasoa** [comment] 2024-11-16 22:01
Hello ! The timeout in sqlpage.fetch is configurable: https://sql.datapage.app/functions.sql?function=fetch#function

You can run

```sql
set request = json_object(
    'timeout_ms', 10000
    'url', $url
);
set api_results = sqlpage.fetch($request);
```

to wait for the answer for 10 seconds instead of the default 5 seconds.


However, the nominatim api should not be that slow to answer. You can ensure that you are following their usage policy: https://operations.osmfoundation.org/policies/nominatim/

If you need an api with more generous limits, you may want to turn to [a paid service](https://wiki.openstreetmap.org/wiki/Nominatim#Alternatives_.2F_Third-party_providers), or to [host your own nominatim instance](https://nominatim.org/release-docs/latest/admin/Installation/)

**Comment by lovasoa** [comment] 2024-11-16 22:02
I am closing this since this is apparently not a bug in SQLPage, but feel free to continue the discussion below, or to reopen the issue if you think this is indeed a bug.

**Closed by lovasoa** 2024-11-16 22:02 UTC
Labels: bug

**Comment by srcarvalho12** [comment] 2024-11-18 17:15
In fact, I have already adjusted the timeout_ms to 30000 and even so it still gives a timeout error, the nominatim api I used just for an example, I just copied and pasted it from the example on the SQLPages website, and if I try to open the api in the browser it practically opens instantly

**Comment by srcarvalho12** [comment] 2024-11-18 17:23
In fact now it seems to work normally, but I thank you for the help, anything I'll come back here again, I really appreciate it!
